services:
  redis:
    hostname: redis_host
    container_name: redis_db
    image: redis:7.2.1
    expose:
      - "35680:35680"
    volumes:
      - type: volume
        source: redis-data
        target: /data
      - ./conf:/usr/local/etc/redis:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "0.0.0.0:35680:35680"
    restart: always
    networks:
      - redis-network
      - micro-network
volumes:
  redis-data:
    name: redis-data-volume
    driver: local
networks:
  redis-network:
    name: redis-network
    driver: bridge
  micro-network:
    external: false
    driver: bridge
    name: micro-network
