services:
  seata:
    hostname: seata
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./conf:/seata-server/conf
    ports:
      - 0.0.0.0:7091:7091
      - 0.0.0.0:8091:8091
    expose:
      - 7091
    container_name: seata
    restart: no
    networks:
      - seata_network
      - micro_network
volumes:
  seata_data:
    name: seata_data
    driver: local
networks:
  seata_network:
    name: seata_network
    driver: bridge
  micro_network:
    external: false
    name: micro_network
    driver: bridge
